name: Update arXiv Articles

on:
  schedule:
    - cron: '1 0 * * *'  # utc time
  push:
    branches:
      - main

jobs:
  update-arxiv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install feedparser

      - name: Send to astrobaijc
        run: python arxiv2mail.py --target astrobaijc@gmail.com

      - name: Send to ffchristy794
        run: python arxiv2mail.py --target ffchristy794@gmail.com
      

